### PR TITLE
Require sequencing_date at the API level but not the database level

### LINKED ISSUE #223: Require sequencing_date at the API level but not the database level

### PR DESCRIPTION
**Pull request by Madelinehazel**
closes #223

```
curl -X POST \
    -H "Content-Type: application/json"  \
    --data '{
            "tissue_sample_id": "1",
            "dataset_type": "CES",
            "input_hpf_path": "/hpf/CES",
            "notes": "blahblah",
            "condition": "GermLine",
            "extraction_protocol": "Something",
            "capture_kit": "capture kit x",
            "read_length": "150",
            "read_type": "PairedEnd",
            "discriminator": "dataset",
            "sequencing_date": "2020-12-04"
        }' \
    localhost:3000/api/datasets
```

### CODE REVIEW

**Comment by kevinlul** [comment]
`/api/_bulk` should also be affected but I happened to change it a bit in #253

**Comment by kevinlul** [comment]
Should be unblocked now for applying the requirements to `/api/_bulk`

**Comment by Madelinehazel** [comment]
test bulk endpoint: 
curl -X POST \
    -H "Content-Type: application/json"  \
    --data '[{
            "family_codename": "1001",
            "participant_codename": "1411",
            "tissue_sample": "Blood",
            "tissue_sample_type": "Blood",
            "dataset_type": "WGS",
            "condition": "GermLine",
            "sequencing_date": "2020-12-17"
        }]' \
    localhost:3000/api/_bulk

**Review by kevinlul — APPROVED** [review]
LGTM

**Review by delvinso — APPROVED** [review]

**Pull request merged**
