### PR TITLE
React: add CSV uploads via react-file-drop library

### PR DESCRIPTION
**Pull request by frewmack**
The general layout is in place for these upload forms. 
TODO: 
- ~~[ ] The fields need to align with those in the design document~~ Move to new branch
- [x] Actual upload depends via #45

### CODE REVIEW

**Review by kevinlul — COMMENTED** [review]
Noting some tasks for this branch

- [x] merge or rebase onto latest master
- [ ] get rid of the link to existing dataset in the modals
- [ ] enumerations can be fetched from the backend now but that only relates to the manual portion

more to come

**Comment by frewmack** [comment]
The file upload should work as intended. The datasets page pulls uploaded records when you upload.

Currently there is no feedback on success or error. I'm thinking of adding a reusable Snackbar component to utils and adding action feedback in a separate branch for all user controls.

**Comment by frewmack** [comment]
Moving the manual form entry issue to a separate branch. After the meeting with CHEO, I think it's better that we take extra care in making the manual form. The CSV upload works as-is.

**Review by kevinlul — COMMENTED** [review]
Is it intended that the drop area expands when dragged over?

**Comment by frewmack** [comment]
> 
> 
> Is it intended that the drop area expands when dragged over?

Yes. The button needs to 'catch' the file, so it expands to make that easier.

**Review by kevinlul — APPROVED** [review]

**Pull request merged**
